package com.michael.kidquest.greendao.model;

import com.michael.kidquest.greendao.custommodel.DifficultyLevel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUEST".
 */
public class Quest {

    private Long id;
    /** Not-null value. */
    private String title;
    private String description;
    private boolean completed;
    /** Not-null value. */
    private DifficultyLevel difficultyLevel;
    /** Not-null value. */
    private java.util.Date dateAdded;
    private java.util.Date expiryDate;

    public Quest() {
    }

    public Quest(Long id) {
        this.id = id;
    }

    public Quest(Long id, String title, String description, boolean completed, DifficultyLevel difficultyLevel, java.util.Date dateAdded, java.util.Date expiryDate) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.completed = completed;
        this.difficultyLevel = difficultyLevel;
        this.dateAdded = dateAdded;
        this.expiryDate = expiryDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean getCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    /** Not-null value. */
    public DifficultyLevel getDifficultyLevel() {
        return difficultyLevel;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDifficultyLevel(DifficultyLevel difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    /** Not-null value. */
    public java.util.Date getDateAdded() {
        return dateAdded;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateAdded(java.util.Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    public java.util.Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(java.util.Date expiryDate) {
        this.expiryDate = expiryDate;
    }

}
