package com.michael.kidquest.greendao.model;

import com.michael.kidquest.greendao.custommodel.DifficultyLevel;

import java.util.Date;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "QUEST".
 */
public class Quest implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String title;
    private String description;
    private boolean completed;
    private boolean confirmed;
    /** Not-null value. */
    private DifficultyLevel difficultyLevel;
    /** Not-null value. */
    private Date dateAdded;
    private Date expiryDate;
    private int current_reward;
    private int xp_reward;


    public Quest() {
    }

    public Quest(Long id) {
        this.id = id;
    }

    public Quest(Long id, String title, String description, boolean completed, boolean confirmed, DifficultyLevel difficultyLevel, Date dateAdded, Date expiryDate) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.completed = completed;
        this.confirmed = confirmed;
        this.difficultyLevel = difficultyLevel;
        this.dateAdded = dateAdded;
        this.expiryDate = expiryDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean getCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    public boolean getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    /** Not-null value. */
    public DifficultyLevel getDifficultyLevel() {
        return difficultyLevel;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDifficultyLevel(DifficultyLevel difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    /** Not-null value. */
    public Date getDateAdded() {
        return dateAdded;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public int getCurrentReward() {
        return current_reward;
    }

    public int getXpReward() {
        return xp_reward;
    }
}
