package com.michael.kidquest.model;

import com.michael.kidquest.custommodel.DifficultyLevel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DIFFICULTY".
 */
public class Difficulty {

    private Long id;
    private DifficultyLevel difficultyLevel;
    private Integer gold;
    private Integer experience;

    public Difficulty() {
    }

    public Difficulty(Long id) {
        this.id = id;
    }

    public Difficulty(Long id, DifficultyLevel difficultyLevel, Integer gold, Integer experience) {
        this.id = id;
        this.difficultyLevel = difficultyLevel;
        this.gold = gold;
        this.experience = experience;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public DifficultyLevel getDifficultyLevel() {
        return difficultyLevel;
    }

    public void setDifficultyLevel(DifficultyLevel difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    public Integer getGold() {
        return gold;
    }

    public void setGold(Integer gold) {
        this.gold = gold;
    }

    public Integer getExperience() {
        return experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

}
